# wrangler.toml
name = 'sabriev-worker-share'
main = "src/index.js"
compatibility_date = "2026-03-22"

[vars]
SITE_ORIGIN = "https://sabriev.com"
SUPABASE_URL = "https://ymeanxgocsvaqeboljhh.supabase.co"
FALLBACK_IMAGE = "https://sabriev.com/images/events-og.jpg"
